module.exports = {
  printWidth: 80,
  arrowParens: 'avoid',
  singleQuote: true,
  jsxDoubleQuote: true,
  singleAttributePerLine: true,
  tabWidth: 2,
  useTabs: true,
  bracketSpacing: true,
  proseWrap: 'always',
  formatOnSave: true,
  semi: true,
  tailwindConfig: './tailwind.config.ts',
  plugins: ['prettier-plugin-tailwindcss'],
};
